// 自动生成 —— 标题栏搜索框的分区 / 参数行索引，勿手改。
// 生成器：scripts/cmd-index.mjs（electron-vite dev / build 起步时由 cmdIndexPlugin 自动刷新，模板改了随手重生成；
// 也可手动 node scripts/cmd-index.mjs）。口径见生成器头注；packages/core/test/cmdIndex.test.mjs 校验本文件与模板同步。
export default [
  {"view":"constellation","key":"constellation-top","title":null,"items":[{"label":"轨道类型"},{"label":"布局"},{"label":"星座名称"},{"label":"轨道倾角 i"},{"label":"轨道高度 h"},{"label":"升交点赤经 Ω"},{"label":"方向"},{"label":"远地点高度 hₐ"},{"label":"近地点高度 hₚ"},{"label":"升交点经度 λ"},{"label":"近地点幅角 ω"},{"label":"星下点经度 λ"},{"label":"远地点经度 λₐ"},{"label":"地方时"},{"label":"由谁定"},{"label":"轨道形状"},{"label":"标识颜色"},{"label":"聚焦"},{"label":"轨迹长度"},{"label":"轨迹圈数"},{"label":"轨迹周期"},{"label":"按轨道面配色"}]},
  {"view":"gxt","key":"gxt-top","title":null,"items":[{"label":"添加卫星"},{"label":"频段"},{"label":"自定义"},{"label":"线粗"}]},
  {"view":"gxt","key":"gxt-disp","title":"显示选项","items":[{"label":"字号"},{"label":"大小"},{"label":"显示波束名"},{"label":"显示波束中心"},{"label":"显示数值标签"}]},
  {"view":"poly","key":"poly-list","title":"协调区多边形","items":[{"label":"数值"},{"label":"轨位"},{"label":"卫星"},{"label":"填充"},{"label":"线粗"},{"label":"字号"}]},
  {"view":"poly","key":"poly-disp","title":"显示与操作","items":[{"label":"顶点大小"},{"label":"扩/缩幅度"}]},
  {"view":"antenna","key":"grd-tree","title":"卫星 / 天线","items":[]},
  {"view":"beams","key":"beams-top","title":null,"items":[{"label":"卫星"}]},
  {"view":"beams","key":"bs-mode","title":null,"items":[{"label":"组名"}]},
  {"view":"beams","key":"bs-settings","title":"波束设置","items":[{"label":"设置名"}]},
  {"view":"beams","key":"bs-antp","title":"天线参数","items":[{"label":"设计频率"},{"label":"仿真频率"},{"label":"馈源直径"},{"label":"馈源模型"},{"label":"偏置净空/D"},{"label":"极化类型"},{"label":"覆盖方式"},{"label":"天线口径"},{"label":"3dB 宽"},{"label":"焦距"},{"label":"馈源间距"}]},
  {"view":"beams","key":"bs-pam","title":"天线参数","items":[{"label":"辐射单元数"},{"label":"单元间距"},{"label":"设计频率"},{"label":"口径效率"},{"label":"单元因子 R"},{"label":"三角晶格（等边 dx=√3/2·dy；Nx 需偶）"},{"label":"应用单元因子（关闭＝仅看阵因子 / 栅瓣）"}]},
  {"view":"beams","key":"bs-place","title":"放置波束","items":[{"label":"波束间距"},{"label":"蜂窝布满"},{"label":"相切吸附","hint":"点击或拖动至边界附近自动相切"}]},
  {"view":"beams","key":"bs-style","title":"轮廓与编号","items":[{"label":"轮廓颜色"},{"label":"线型"},{"label":"编号字号"},{"label":"编号颜色"},{"label":"线宽"},{"label":"显示波束编号"},{"label":"粗体"}]},
  {"view":"beams","key":"bs-freq","title":"频率计划","items":[{"label":"颜色数"},{"label":"填充透明"},{"label":"显示配色（波束填充 + 轮廓着色）"}]},
  {"view":"beams","key":"bs-pcov","title":"覆盖区域","items":[{"label":"指向误差"}]},
  {"view":"beams","key":"bs-st","title":"站点栅","items":[{"label":"显示"},{"label":"数字大小"},{"label":"栅密度"},{"label":"栅类型"},{"label":"旋转"},{"label":"中心偏移"},{"label":"生成"},{"label":"站点大小"},{"label":"类型"},{"label":"目标偏置"},{"label":"粗体"}]},
  {"view":"beams","key":"bs-excit","title":"星上激励指令","items":[]},
  {"view":"beams","key":"bs-refl","title":"反射面模型","items":[{"label":"口径直径"},{"label":"焦距"},{"label":"馈电方式"},{"label":"馈源锥度"},{"label":"设计频率"},{"label":"仿真频率"},{"label":"极化类型"},{"label":"偏置净空/D"}]},
  {"view":"beams","key":"bs-cov","title":"覆盖区域","items":[{"label":"指向误差"}]},
  {"view":"beams","key":"bs-st","title":"站点栅","items":[{"label":"显示"},{"label":"数字大小"},{"label":"栅密度"},{"label":"栅类型"},{"label":"旋转"},{"label":"中心偏移"},{"label":"生成"},{"label":"站点大小"},{"label":"类型"},{"label":"目标偏置"},{"label":"粗体"}]},
  {"view":"beams","key":"bs-gen","title":"生成天线","items":[]},
  {"view":"vis","key":"vis-target","title":"分析目标","items":[{"label":"卫星集"},{"label":"仰角门限","hint":"仰角 ≥ 该值判为可见 / 被覆盖"},{"label":"目标"}]},
  {"view":"vis","key":"vis-list","title":null,"items":[{"label":"图标"},{"label":"时窗"},{"label":"区域"},{"label":"纬度"},{"label":"经度"},{"label":"网格步长"},{"label":"采样"},{"label":"指标"},{"label":"配色"},{"label":"透明度"},{"label":"名字大小"},{"label":"选择"}]},
  {"view":"env","key":"env-src","title":"数据场","items":[{"label":"字段"},{"label":"格距"}]},
  {"view":"env","key":"env-style","title":"配色与值域","items":[{"label":"配色"},{"label":"填色"},{"label":"值域"},{"label":"透明度"},{"label":"上下限"},{"label":"海洋透明（按 P.1511 地形 ≤0 判海）"}]},
  {"view":"env","key":"env-contour","title":"等值线","items":[{"label":"级差"},{"label":"画等值线"},{"label":"沿线标数值（仅平面图）"}]},
  {"view":"envLive","key":"lv-fetch","title":"数据获取","items":[{"label":"区域"},{"label":"多边形"},{"label":"纬度"},{"label":"经度"},{"label":"格距"},{"label":"时段"},{"label":"帧间隔"}]},
  {"view":"envLive","key":"lv-link","title":"链路参数","items":[{"label":"目标"},{"label":"轨位"},{"label":"卫星"},{"label":"星下点"},{"label":"轨道高度"},{"label":"频率"},{"label":"最低仰角"},{"label":"路径模型"},{"label":"云衰"}]},
  {"view":"envLive","key":"lv-src","title":"数据场","items":[{"label":"字段"},{"label":"渲染格距"},{"label":"渲染点数上限"}]},
  {"view":"envLive","key":"lv-style","title":"配色与值域","items":[{"label":"配色"},{"label":"填色"},{"label":"值域"},{"label":"透明度"},{"label":"上下限"},{"label":"海洋透明（ITU-R P.1511 高程 ≤ 0 判为海域）"}]},
  {"view":"focus","key":"foc-orb","title":"轨道线","items":[{"label":"颜色"},{"label":"线粗"},{"label":"透明度"},{"label":"线型"}]},
  {"view":"focus","key":"foc-trk","title":"星下点轨迹","items":[{"label":"形式"},{"label":"颜色"},{"label":"线粗"},{"label":"透明度"},{"label":"线型"},{"label":"区域填充","hint":"带内填色；0＝不填"},{"label":"填充颜色"},{"label":"轨迹长度"},{"label":"轨迹圈数"},{"label":"轨迹周期"}]},
  {"view":"focus","key":"foc-fp","title":"覆盖圈","items":[{"label":"口径"},{"label":"线颜色"},{"label":"线粗"},{"label":"透明度"},{"label":"线型"},{"label":"区域填充","hint":"圈内填色（画在 GRD 覆盖场之下，叠加区仍以覆盖图为准）；0＝不填"},{"label":"填充颜色"},{"label":"波束全锥角"},{"label":"最低仰角"}]},
  {"view":"focus","key":"foc-cone","title":"覆盖锥","items":[{"label":"锥面","hint":"锥侧面填色，0＝只留母线"},{"label":"锥面颜色"},{"label":"母线根数","hint":"沿方位等分画几条母线，0＝只留锥面"},{"label":"母线颜色"},{"label":"母线线粗"},{"label":"母线透明度"},{"label":"母线线型"}]},
  {"view":"focus","key":"foc-mk","title":"卫星标记","items":[{"label":"大小"},{"label":"颜色"},{"label":"星座点云","hint":"整个星座的星点（仅 3D 球体）。关掉后地图上只剩聚焦星的标记，星点也不再可点选"},{"label":"在轨点","hint":"卫星真实在轨位置上的大号圆点，颜色跟随该星在星座里的配色"},{"label":"星下点图标"},{"label":"高亮环","hint":"套在聚焦星本体上的圆环（在轨高度，不是星下点）"}]},
  {"view":"geo","key":"geo-proj","title":"2D 投影","items":[{"label":"投影"},{"label":"画面中心"},{"label":"常用"},{"label":"投影中心"},{"label":"星下点"},{"label":"经度"},{"label":"纬度"},{"label":"高度"},{"label":"卫星"},{"label":"搜索"},{"label":"光标读数"},{"label":"中心纬度"},{"label":"标准纬线"},{"label":"当前"}]},
  {"view":"geo","key":"geo-space","title":"宇宙空间","items":[{"label":"夜区强度","hint":"太阳高度角 −18° 以下（全黑夜）的不透明度"},{"label":"日下点","hint":"太阳直射点（时间轴当前时刻）"},{"label":"星空亮度"},{"label":"辉光强度"},{"label":"眩光强度"},{"label":"分辨率"},{"label":"亮度"},{"label":"夜区颜色"},{"label":"线颜色"},{"label":"线粗"},{"label":"线透明度"},{"label":"星空","hint":"约 110 颗亮星按真实赤经赤纬与视星等、其余按星等计数律补足，另有银河带；静态不闪，随恒星时转动；仅 3D 球体"},{"label":"大气辉光","hint":"地球临边的大气散射：昼侧亮蓝、夜侧几乎不见、晨昏线附近偏暖，与晨昏效果同一个太阳方向；仅 3D 球体"},{"label":"太阳","hint":"日面 + 柔和眩光，沉到地球背后时淡出；仅 3D 球体"},{"label":"地球影像","hint":"真彩卫星影像，3D 球体与平面图同一份；「高精」档平面图用瓦片金字塔、3D 球体用 16K 整幅（显卡纹理上限不足 16384 时自动落到 8K）"},{"label":"晨昏效果","hint":"夜半球按太阳高度角从 0° 到 −18° 平滑压暗（民用 −6° / 航海 −12° / 天文 −18° 曙暮光），卫星模型按太阳方向受光、进地影变暗；不勾时地球与卫星全亮。3D 球体与平面图"},{"label":"晨昏线","hint":"太阳中心高度角 0° 的昼夜分界线；晨昏效果不勾时自带一层夜区阴影（勾着时夜区归晨昏效果）。3D 球体与平面图"}]},
  {"view":"geo","key":"geo-ocean","title":"配色","items":[{"label":"自定义底色"},{"label":"国家"}]},
  {"view":"geo","key":"geo-border","title":"边界线","items":[{"label":"预设"},{"label":"颜色"},{"label":"线粗"},{"label":"透明度"},{"label":"间隔"},{"label":"线型"},{"label":"行政区界按缩放淡出","hint":"全球视角下二级行政区界完全淡出、一级降到 0.3，拉近后线性恢复；国界与海岸线不参与"}]},
  {"view":"geo","key":"geo-name","title":"地名","items":[{"label":"名称"},{"label":"字号"},{"label":"颜色"},{"label":"透明度"},{"label":"搜索"},{"label":"粗体"}]},
  {"view":"geo","key":"geo-adm","title":"行政区","items":[{"label":"国家"},{"label":"地级市"}]},
  {"view":"geo","key":"geo-chain","title":"岛链","items":[{"label":"名称"},{"label":"颜色"},{"label":"线粗"},{"label":"透明度"},{"label":"线型"},{"label":"字号"}]},
  {"view":"geo","key":"geo-crs","title":"坐标系","items":[{"label":"大地基准"},{"label":"坐标格式"}]},
  {"view":"geo","key":"geo-pov","title":"地图视角","items":[{"label":"视角"}]},
  {"view":"markers","key":"mk-points","title":"点标记","items":[{"label":"纬度"},{"label":"经度"},{"label":"圈大小"},{"label":"盘颜色"},{"label":"盘透明度"},{"label":"圈颜色"},{"label":"数字颜色"},{"label":"符号"},{"label":"颜色"},{"label":"大小"},{"label":"透明度"},{"label":"描边","hint":"描边宽 ÷ 符号直径，0＝不描边"},{"label":"字号"},{"label":"位置"},{"label":"描边颜色"},{"label":"显示序号","hint":"点标记画成带序号的圈（圈 1、圈 2）；序号即下方列表与点标记表格的行号"},{"label":"显示坐标"}]},
  {"view":"markers","key":"mk-stations","title":"地球站","items":[{"label":"纬度"},{"label":"经度"},{"label":"名称"},{"label":"大小"},{"label":"透明度"},{"label":"字号"},{"label":"颜色"},{"label":"位置"},{"label":"跟踪"},{"label":"显示名称"}]},
  {"view":"markers","key":"mk-traj","title":"轨迹","items":[{"label":"航行色"},{"label":"飞行色"},{"label":"线粗"},{"label":"透明度"},{"label":"线型"},{"label":"大小","hint":"0＝不画航点圆点"},{"label":"字号"},{"label":"颜色"},{"label":"速度"},{"label":"起始"},{"label":"巡航高度"},{"label":"航点"},{"label":"显示图标","hint":"航迹头（末航点）上画一枚俯视矢量图标：航行＝船舶、飞行＝飞机，朝向取末段走向"},{"label":"显示航迹名","hint":"在航迹头旁标出航迹名"}]},
  {"view":"satcov","key":"satcov-tree","title":"卫星 / 天线","items":[]},
  {"view":"satcov","key":"satcov-shell","title":"轨道壳层","items":[{"label":"掠地高度"},{"label":"网格间隔"},{"label":"纬线范围"},{"label":"线宽"},{"label":"透明度"},{"label":"线型"},{"label":"显示壳层参照网"}]},
  {"view":"settings","key":"set-look","title":"外观","items":[]},
  {"view":"settings","key":"set-lang","title":"语言","items":[]},
  {"view":"settings","key":"set-font","title":"界面字体","items":[{"label":"西文"},{"label":"中文"}]},
  {"view":"settings","key":"set-quality","title":"显示设置","items":[{"label":"渲染分辨率","hint":"超采样倍率，对性能影响最大"},{"label":"底图精细化"},{"label":"覆盖网格"},{"label":"渲染帧率","hint":"帧率上限越低越省电"},{"label":"球体细分","hint":"地球网格精度"},{"label":"MSAA 抗锯齿"}]},
  {"view":"settings","key":"set-basic","title":"基础设置","items":[{"label":"地球自转","hint":"惯性视角：相机固定在惯性空间，地球随仿真时钟东转；相机跟随：相机随地球一起转，地面不动"},{"label":"拖拽阻尼","hint":"拖动的粘滞感：0% 直连，越大越重、停得越柔；地面不会滑过光标"},{"label":"3D 滚轮缩放","hint":"每滚一格，底部状态栏的缩放读数走多少个百分点"},{"label":"2D 滚轮缩放","hint":"每滚一格，底部状态栏的缩放读数走多少个百分点"}]}
]
