// 标题栏搜索框的【匹配关键词】—— 只参与检索，绝不显示。
// 同义词 / 英文名 / 缩写 / 用户口头叫法，让「dark」「TLE」「暗色」「弯管」都能落到对应命令上。
// 单独成文件：这些串不是界面文本，scripts/i18n-scan.mjs 把本文件排除在词典覆盖率审计之外。
// 键 = 命令标题（菜单项 / 活动栏视图 / 文件管理页签）或命令 id（分区、页内动作）。

// —— 按标题：菜单项 + 活动栏视图（App.vue 登记时按 label 取）——
export const CMD_KW = {
  '文件管理…': ['file manager', 'library', 'files', '星历', '方向图', 'GRD', 'GXT', 'KML', 'MODCOD', '导入', '导出', '资料库'],
  '转发器频率计划…': ['frequency plan', 'transponder', 'freq plan', '频率分配', '转发器', '频率', '信标'],
  '空间态势报告…': ['ssa', 'space situational awareness', 'satcat', 'catalog', 'celestrak', '编目', '态势', '在轨', '发射', '陨落', '卫星组', 'report', '碎片', '所有者'],
  '导入星历文件…': ['TLE', 'OMM', '3LE', 'CSV', 'KVN', 'import', 'ephemeris', 'CelesTrak', '星历', '两行根数', '离线'],
  '退出': ['exit', 'quit', 'close', '关闭窗口'],
  'GSO 透明转发链路预算': ['GEO', 'link budget', 'bent pipe', 'transparent', '透明转发', '链路预算', '同步轨道', '静止轨道', '弯管'],
  'NGSO 透明转发链路预算': ['LEO', 'MEO', 'HEO', 'link budget', 'non-GSO', '非同步', '非静止', '星座链路', '链路预算', 'SGP4'],
  '再生处理（OBP）链路预算': ['OBP', 'regenerative', 'onboard processing', 'link budget', '再生式', '星上处理', '星间', '激光', '链路预算'],
  '端到端链路预算（多跳 / 混合转发）': ['E2E', 'end to end', 'multi hop', 'chain', '多跳', '混合转发', 'ISL', '双跳', '链路预算'],
  '日凌预报（GSO）': ['sun outage', 'sun transit', 'solar', '日凌', '太阳', '中断', 'excel', 'ephemeris', '多站', '星历'],
  '雨衰计算': ['rain attenuation', 'rain fade', 'P.618', 'ITU', '降雨', '雨衰', '衰减', '可用度'],
  '干扰分析（C/I）': ['interference', 'C/I', 'ASI', 'CCI', 'XPI', '邻星', '同频', '交叉极化', '干扰'],
  'PFD EIRP Mask 生成器': ['PFD', 'EIRP', 'mask', 'S.1503', 'ITU', '掩模', '功率通量密度'],
  '3D 球体': ['3D', 'globe', 'sphere', '球体', '三维', '地球'],
  '2D 平面图': ['2D', 'flat', 'map', 'plane', '平面', '二维', '世界地图'],
  '工具栏': ['toolbar', '图标栏'],
  '侧栏': ['sidebar', 'side panel', 'panel', '面板', '侧边栏'],
  '日志窗格': ['log', 'console', 'output', '日志', '输出'],
  '高清 PNG · 2×': ['png', 'image', 'export', 'screenshot', '图片', '截图', '高清', '导出图'],
  '高清 PNG · 4×': ['png', 'image', 'export', 'screenshot', '图片', '截图', '高清', '导出图'],
  '高清 PNG · 8K': ['png', 'image', 'export', '8k', 'uhd', '图片', '高清', '导出图'],
  '矢量 PDF': ['pdf', 'vector', 'export', '矢量', '导出', '文档'],
  '导出 GXT（对地）': ['gxt', 'export', 'contour', '覆盖', '等值线', '导出'],
  '导出 KML（对地）': ['kml', 'google earth', 'export', '覆盖', '导出'],
  '发送到小程序…': ['miniapp', 'wechat', 'share', 'upload', '微信', '小程序', '分享', '上传', '密钥'],
  '绑定小程序账号…': ['bind', 'wechat', 'account', '微信', '小程序', '认证码', '账号'],
  '设置…': ['settings', 'options', 'preferences', '偏好', '选项', '主题', '语言', '字体', '画质'],
  '微信小程序 LinkLab…': ['LinkLab', 'miniapp', 'wechat', 'app', '小程序', '手机'],
  '检查更新…': ['update', 'upgrade', 'check for updates', 'new version', '升级', '新版本', '更新', '版本'],
  '关于卫星仿真平台…': ['about', 'version', 'license', '版本', '激活', '授权', '设备ID', '关于'],
  // 活动栏视图
  '星座': ['constellation', 'satellites', 'groups', '卫星', '卫星组', '卫星搜索', '分组', '星座生成'],
  '对地覆盖分析': ['coverage', 'GRD', 'antenna', 'footprint', 'pattern', '覆盖', '天线', '方向图', '对地', '性能指标'],
  '对星覆盖分析': ['shell', 'orbit shell', 'inter-satellite coverage', '对星', '壳层', '轨道壳'],
  'Polygon（协调区）': ['polygon', 'coordination area', '协调区', '多边形', '绘制'],
  '可见性分析': ['visibility', 'access', 'STK', 'pass', '可见', '过境', '仰角门限', '覆盖网格'],
  '天线波束合成': ['beam synthesis', 'shaped', 'reflector', 'phased array', 'PAM', '波束', '赋形', '反射面', '相控阵', '多馈源'],
  'GXT/KML 显示': ['GXT', 'KML', 'coverage contour', '覆盖等值线', '覆盖图', '覆盖库'],
  '标记': ['markers', 'points', 'earth station', 'trajectory', '标记', '地球站', '点', '航迹', '轨迹', '船', '飞机'],
  '环境场': ['ITU', 'rain rate', 'environment', 'climate', 'R0.01', '环境', '雨量', '降雨率', '水汽', '雨高', '等温线', '云'],
  '实时气象': ['weather', 'GFS', 'live', 'forecast', 'QWeather', '实时', '气象', '云图', '预报', '降水', '和风'],
  '聚焦卫星': ['focus', 'selected satellite', 'display style', '聚焦', '轨道线', '覆盖圈', '样式'],
  '地图设置': ['map settings', 'basemap', 'projection', 'border', 'label', '地图', '底图', '投影', '国界', '地名', '晨昏线', '坐标系', '配色'],
  // 文件管理页签
  '轨道星历': ['OMM', 'TLE', 'ephemeris', 'orbit', '星历', '自定义卫星', '根数'],
  '天线方向图': ['GRD', 'pattern', 'antenna', 'STK', 'ACP4', 'Eutelsat', '方向图', '天线', '导出方向图'],
  '频率计划': ['frequency plan', 'transponder', '频率计划文件', '转发器'],
  'MODCOD 表': ['modcod', 'modulation', 'coding', 'DVB-S2', 'threshold', '调制', '编码', '门限', '标准'],
  'GXT/KML 管理': ['gxt', 'kml', 'coverage', '覆盖库', '覆盖文件'],
  // 设置项
  '外观': ['theme', 'appearance', 'dark mode', 'light mode', '主题', '深色模式', '暗色', '夜间', '浅色', '外观'],
  '语言': ['language', 'english', 'chinese', '中文', '英文', '界面语言'],
  '界面字体': ['font', 'ui font', 'typeface', '字体', '等线', '雅黑', '西文', '中文字体'],
  '显示设置': ['quality', 'display', 'performance', 'resolution', 'fps', '画质', '分辨率', '帧率', '性能', '底图精细化'],
  'MSAA 抗锯齿': ['msaa', 'antialias', 'anti-aliasing', '抗锯齿', '锯齿'],
  '播放仿真时钟': ['play', 'animate', 'animation', 'clock', 'time', '播放', '动画', '时间轴', '仿真'],
  '暂停仿真时钟': ['pause', 'stop', 'clock', '暂停', '停止', '时间轴'],
  '仿真时钟回到实时': ['live', 'now', 'real time', 'clock', '实时', '当前时间', '现在']
}

// —— 按 id：侧栏分区（sec.<首个 key>）与星座地图页登记的动作 ——
export const ID_KW = {
  'sec.gxt-disp': ['display options', 'gxt', 'kml', '覆盖图显示'],
  'sec.poly-list': ['polygon list', 'coordination', '多边形列表', '导入', '绘制'],
  'sec.poly-disp': ['polygon display', '多边形显示', '调点', '扩缩'],
  'sec.grd-tree': ['antenna tree', 'satellite', 'GRD', '天线树', '波束', '方向图', '仰角线'],
  'sec.bs-settings': ['beam settings', '波束参数', '高斯', '赋形', '相控阵'],
  'sec.bs-antp': ['antenna parameters', 'reflector', 'butler', '口径', '焦距', '馈源', '相控阵'],
  'sec.bs-place': ['place beams', 'beam layout', '波束布局', '点图放置'],
  'sec.bs-style': ['outline', 'numbering', '轮廓', '编号', '样式'],
  'sec.bs-freq': ['frequency plan', 'color', '频率复用', '配色', '色号'],
  'sec.bs-pcov': ['coverage area', 'polygon', '赋形', '协调区'],
  'sec.bs-st': ['station grid', 'stations', '站点', '栅格', '赋形'],
  'sec.bs-excit': ['excitation', 'PAM', 'phased array', '激励', '相控阵', '端口'],
  'sec.bs-refl': ['reflector model', 'offset', '偏置反射面', '赋形'],
  'sec.env-src': ['data field', 'ITU', 'rain rate', '降雨率', '水汽', '雨高', '海拔'],
  'sec.env-style': ['color scale', 'range', '色标', '值域', '配色'],
  'sec.env-contour': ['contour', 'isoline', '等值线', '环境场'],
  'sec.lv-fetch': ['fetch', 'download', 'GFS', 'QWeather', '获取', '下载', '和风', '实时气象'],
  'sec.lv-link': ['link parameters', 'target satellite', '目标星', '频率', '仰角', '瞬时雨衰'],
  'sec.lv-src': ['data field', 'weather', '降水', '云量', '气温', '湿度', '实时气象'],
  'sec.lv-style': ['color scale', 'range', '色标', '值域', '配色', '实时气象'],
  'sec.foc-mk': ['satellite marker', 'icon', '图标', '标记样式', '聚焦'],
  'sec.geo-ocean': ['colors', 'ocean', 'land', '海陆', '海洋', '陆地', '颜色'],
  'sec.geo-border': ['borders', 'coastline', 'boundary', '国界', '海岸线', '省界', '争议'],
  'sec.geo-name': ['labels', 'place names', '注记', '国名', '城市', '海域名'],
  'sec.geo-crs': ['CRS', 'datum', 'WGS84', 'CGCS2000', 'GCJ02', 'UTM', 'MGRS', '大地基准', '坐标格式', '度分秒'],
  'sec.geo-pov': ['view', 'camera', 'center', '画面中心', '视角', '切口'],
  // 星座地图页登记的动作与图层开关
  'const.wizard': ['walker', 'constellation', 'generate', '星座生成器', '新建星座', '轨道面'],
  'const.frame': ['rotate', 'spin', 'inertial', 'fixed', 'earth rotation', '自转', '惯性', '跟随', '地固'],
  'const.live': ['live', 'real time', 'clock', '实时', '当前时间'],
  'const.sendMini': ['miniapp', 'wechat', '微信', '小程序', '卫星组', '自定义卫星', '星座'],
  'const.import': ['import', 'ephemeris', 'stk', 'oem', 'ccsds', 'sp3', 'tle', 'omm', 'almanac', 'yuma', 'sem',
    '导入', '星历', '外部星历', '点序列', '精密星历', '年历'],
  'poly.draw': ['polygon', 'draw', 'coordination', '协调区', '画多边形', '绘制'],
  'poly.import': ['polygon', 'import', 'gxt', 'kml', '协调区', '导入'],
  'grd.addSat': ['satellite', 'add', 'antenna tree', '自定义卫星', '天线树', '关联卫星'],
  'grd.addElev': ['elevation', 'contour', 'elevation line', '等仰角线', '仰角'],
  'mk.pointsTable': ['points', 'marker', 'excel', 'table', '批量', '表格'],
  'mk.stationsTable': ['earth station', 'excel', 'table', '批量', '表格', '站址'],
  'mk.points': ['points', 'marker', 'pin', '标记点'],
  'mk.stations': ['earth station', 'ground station', 'es', '站'],
  'mk.traj': ['trajectory', 'track', 'route', '航迹', '船', '飞机'],
  'geo.imagery': ['imagery', 'satellite image', 'basemap', '真彩', '卫星影像', '底图'],
  'geo.adm': ['province', 'admin', 'state', '省界', '省', '行政区划'],
  'geo.chain': ['island chain', '第一岛链', '第二岛链'],
  'geo.term': ['terminator', 'day night', 'night', '夜区', '昼夜', '太阳'],
  'geo.proj': ['projection', 'mercator', 'equal earth', 'robinson', 'albers', 'azimuthal', '投影', '墨卡托', '罗宾逊', '阿尔伯斯', '方位等距', '等距圆柱', '等积'],
  'foc.orb': ['orbit', 'orbit line', '轨道'],
  'foc.trk': ['ground track', 'subsatellite', '星下点', '地面轨迹'],
  'foc.fp': ['footprint', 'coverage circle', '覆盖', '仰角圈'],
  'foc.cone': ['cone', 'coverage cone', '锥']
}

export const kwOf = (label) => CMD_KW[label] || []
export const kwId = (id) => ID_KW[id] || []
